2025-04-06 22:31:01,891 - INFO - 🔹 Reading processed dataset...
2025-04-06 22:31:01,912 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 22:31:02,122 - INFO - 📥 No existing schema. Inferring and saving new schema...
2025-04-06 22:31:02,126 - INFO - ✅ New schema saved to: /home/runner/work/MLOPS-Sentiment-Analyzer-Project/MLOPS-Sentiment-Analyzer-Project/Data_Pipeline/validation/schema.pbtxt
2025-04-06 22:31:02,128 - INFO - ✅ Reference stats saved to: /home/runner/work/MLOPS-Sentiment-Analyzer-Project/MLOPS-Sentiment-Analyzer-Project/Data_Pipeline/validation/reference_stats.tfrecord
2025-04-06 22:44:48,158 - INFO - 🔹 Reading processed dataset...
2025-04-06 22:44:48,178 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 22:44:48,384 - INFO - 🔍 Schema exists. Validating against it...
2025-04-06 22:44:48,388 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-06 22:54:54,984 - INFO - 🔹 Reading processed dataset...
2025-04-06 22:54:55,004 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 22:54:55,213 - INFO - 🔍 Schema exists. Validating against it...
2025-04-06 22:54:55,218 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-06 23:25:23,658 - INFO - 🔹 Reading processed dataset...
2025-04-06 23:25:23,678 - INFO - 🔹 Generating statistics from dataset...
2025-04-06 23:25:23,892 - INFO - 🔍 Schema exists. Validating against it...
2025-04-06 23:25:23,897 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 00:08:04,163 - INFO - 🔹 Reading processed dataset...
2025-04-07 00:08:09,623 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 00:08:25,999 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 00:08:26,004 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 00:34:44,110 - INFO - 🔹 Reading processed dataset...
2025-04-07 00:34:44,130 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 00:34:44,209 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 00:34:44,214 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 01:03:29,858 - INFO - 🔹 Reading processed dataset...
2025-04-07 01:03:29,879 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 01:03:29,959 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 01:03:29,963 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-07 04:19:51,483 - INFO - 🔹 Reading processed dataset...
2025-04-07 04:19:51,504 - INFO - 🔹 Generating statistics from dataset...
2025-04-07 04:19:51,584 - INFO - 🔍 Schema exists. Validating against it...
2025-04-07 04:19:51,588 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-08 01:34:36,452 - INFO - 🔹 Reading processed dataset...
2025-04-08 01:34:36,472 - INFO - 🔹 Generating statistics from dataset...
2025-04-08 01:34:36,552 - INFO - 🔍 Schema exists. Validating against it...
2025-04-08 01:34:36,556 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 04:08:39,115 - INFO - 🔹 Reading processed dataset...
2025-04-11 04:08:39,136 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 04:08:39,215 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 04:08:39,220 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
2025-04-11 04:13:33,383 - INFO - 🔹 Reading processed dataset...
2025-04-11 04:13:33,405 - INFO - 🔹 Generating statistics from dataset...
2025-04-11 04:13:33,484 - INFO - 🔍 Schema exists. Validating against it...
2025-04-11 04:13:33,488 - ERROR - ❌ Error during schema validation: module 'tensorflow_data_validation.utils.schema_util' has no attribute 'anomalies_present'
